apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: k8s-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: wprmdev/k8s-webapp
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
            limits:
              memory: "600Mi"
              cpu: "2000m"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: k8s-sample
spec:
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp
  namespace: k8s-sample
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - host: k8s-webapp.hwcloud.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp
                port:
                  number: 80
  ingressClassName: nginx
  tls:
    - hosts: [ "*.hwcloud.com.br" ]
      secretName: hw-cloud-tls